name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pipenv'
    - name: Install dependencies
      run: pipenv sync --dev
    - name: Test
      run: pipenv run pytest -v
